apiVersion: v1
kind: Pod
metadata:
  name: caddy-cloudflared
  labels:
    app: caddy-stack
    version: v1
spec:
  restartPolicy: Always
  nodeSelector:
    kubernetes.io/os: linux
  
  containers:
  - name: caddy
    image: docker.io/library/caddy:latest
    command: ["caddy"]
    args: ["run", "--config", "/config/Caddyfile", "--adapter", "caddyfile"]

    ports:
    - containerPort: 80        # Caddy still listens internally on 80
      hostPort: 1221           # Exposed externally on 1221
      protocol: TCP
      name: http
    - containerPort: 2019
      protocol: TCP
      name: admin

    volumeMounts:
    - name: serv-dir
      mountPath: /config
    - name: caddy-data
      mountPath: /data
    - name: caddy-www
      mountPath: /serv/www

    env:
    - name: TZ
      value: "UTC"

    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"

    livenessProbe:
      httpGet:
        path: /config/
        port: 2019
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3

    readinessProbe:
      httpGet:
        path: /config/
        port: 2019
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3

  - name: cloudflared
    image: docker.io/cloudflare/cloudflared:latest
    args: ["tunnel", "--no-autoupdate", "run"]

    env:
    - name: TUNNEL_TOKEN
      value: "YOUR_TUNNEL_TOKEN"
    - name: TZ
      value: "UTC"

    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "200m"

    livenessProbe:
      exec:
        command: ["sh", "-c", "ps aux | grep -v grep | grep cloudflared"]
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3

    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: ["ALL"]

    volumeMounts:
    - name: tmp
      mountPath: /tmp

  volumes:
  - name: serv-dir
    hostPath:
      path: /serv
      type: Directory
  - name: caddy-data
    hostPath:
      path: /serv/caddy
      type: DirectoryOrCreate
  - name: caddy-www
    hostPath:
      path: /serv/www
      type: Directory
  - name: tmp
    emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: caddy-service
  labels:
    app: caddy-stack
spec:
  type: NodePort
  ports:
  - port: 1221          # Service port exposed
    targetPort: 80      # Still routes to container’s port 80
    protocol: TCP
    name: http
  selector:
    app: caddy-stack
